# -*- coding: utf-8 -*-
"""TDSGA8_App.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cl0sCVpj8OOVjZYPR_4fpycszKUxGKo1
"""

import streamlit as st

st.write("# Largest Number")
st.write("This app finds the largest among the 3 given numbers")

numA = st.number_input("Insert the first number, A")
numB = st.number_input("Insert the second number, B")
numC = st.number_input("Insert the third number, C")

largest = max(numA, numB, numC)

st.write("The largest of the three numbers is: ", largest)